            .text
start:      mv a0, zero
            addi a0, a0, 1
            blt a0, a1, 1
            .word 0x051025

            mv a0, zero
            addi a0, a0, 2
            .word 0x051025

            mv a0, zero
            addi a0, a0, 3
            .word 0x051025

            mv a0, zero
            addi a0, a0, 4
            .word 0x051025

            mv a0, zero
            addi a0, a0, 5
            .word 0x051025

            mv a0, zero
            addi a0, a0, 6
            .word 0x051025

            mv a0, zero
            addi a0, a0, 7
            .word 0x051025

            mv a0, zero
            addi a0, a0, 8
            .word 0x051025

            mv a0, zero
            addi a0, a0, 9
            .word 0x051025

            mv a0, zero
            addi a0, a0, 10
            .word 0x051025


